server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meditrack_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: 86400000 # 24 hours in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
